version: "3.8" # 使用 Docker Compose 文件版本 3.8，根据需要可以更改
services:
  paperai:
    image: 14790897/study:latest
    container_name: study
    ports:
      - "11451:11451" # 映射宿主机和容器的端口
    restart: unless-stopped # 容器退出时重启策略
