name: Learn

on:
  schedule:
    - cron: '30 11 * * 2' # 每周二11时30分开始学习
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: '手动学习'
        type: boolean
        required: true
        default: true
jobs:
  learn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Start Learn
        env:
          KEY: ${{ secrets.KEY }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}

        run: |
          pip3 install -r requirements.txt
          python3 script.py -a -wx=$WECHAT_WEBHOOK $KEY
